server:
  port: 8861

spring:
  application:
    name: eshop-api-gateway

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true