spring:
  application:
    name: product-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 11000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8167/eureka